languageCode = "en"
languageName = "English"
weight = 1
title = "jonam'Log"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January, 2006" # 2006-01-02, 2 January 2006
  favicon = "favicon.ico"
#   logo = "blowfish_pic.png"
#   secondaryLogo = "blowfish_pic.png"
  description = "My awesome website"
  copyright = "&copy; 2025 Manoj. All Rights Reserved."
